write_simulate_sbat <- function(num_tree, num_pheno, num_tip, num_geno) {
  writeLines(c("#!/bin/sh",
               paste0("#SBATCH --job-name=sim_disc_data"),
               paste0("#SBATCH --output=simulate_discrete_data.out"),
               "#SBATCH --mail-user=katiephd@umich.edu",  
               "#SBATCH --mail-type=END",
               "#SBATCH --export=ALL",
               "#SBATCH --partition=standard",
               "#SBATCH --account=esnitkin1",
               "#SBATCH --nodes=1 --ntasks=1 --cpus-per-task=1 --mem=20G --time=240:00:00",
               "cd $SLURM_SUBMIT_DIR",
               "echo $SLURM_SUBMIT_DIR",
               "echo $SLURM_JOB_ID",
               paste("Rscript ../../simulate_data_for_convergence_based_bGWAS/R/simulate_discrete_data.R", num_tree, num_pheno, num_tip, num_geno, sep = " ")),
             paste0(getwd(), "/", "simulate_discrete_data.sbat"),
             sep = "\n")
  
  writeLines(c("#!/bin/sh",
               paste0("#SBATCH --job-name=sim_cont_data"),
               paste0("#SBATCH --output=simulate_continuous_data.out"),
               "#SBATCH --mail-user=katiephd@umich.edu",  
               "#SBATCH --mail-type=END",
               "#SBATCH --export=ALL",
               "#SBATCH --partition=standard",
               "#SBATCH --account=esnitkin1",
               "#SBATCH --nodes=1 --ntasks=1 --cpus-per-task=1 --mem=20G --time=240:00:00",
               "cd $SLURM_SUBMIT_DIR",
               "echo $SLURM_SUBMIT_DIR",
               "echo $SLURM_JOB_ID",
               paste("Rscript ../../simulate_data_for_convergence_based_bGWAS/R/simulate_continuous_data.R", num_tree, num_pheno, num_tip, num_geno, sep = " ")),
             paste0(getwd(), "/", "simulate_continuous_data.sbat"),
             sep = "\n")
}
